//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SEGURIDAD.Models.CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horario_Materia()
        {
            this.Grupos = new HashSet<Grupos>();
        }
    
        public string codigo_horariomateria { get; set; }
        public int horario { get; set; }
        public string materia { get; set; }
        public string docente { get; set; }
    
        public virtual Docentes Docentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupos> Grupos { get; set; }
        public virtual Materia Materia1 { get; set; }
        public virtual horario horario11 { get; set; }
    }
}
