
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVC_SEGURIDAD.Models.CRUD
{

using System;
    using System.Collections.Generic;
    
public partial class MODULOS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MODULOS()
    {

        this.OPERACIONES = new HashSet<OPERACIONES>();

    }


    public int CODMOD { get; set; }

    public string NOMBRE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OPERACIONES> OPERACIONES { get; set; }

}

}
