//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SEGURIDAD.Models.CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_OPERA
    {
        public int CODROLOPERA { get; set; }
        public Nullable<int> CODROL { get; set; }
        public Nullable<int> CODOPERA { get; set; }
    
        public virtual OPERACIONES OPERACIONES { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
