//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Alumnos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Alumnos()
    {
        this.Alumnos_Horario = new HashSet<Alumnos_Horario>();
    }

    public string id_alumno { get; set; }
    public string nombre { get; set; }
    public string apellido { get; set; }
    public string correo { get; set; }
    public string carrera { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Alumnos_Horario> Alumnos_Horario { get; set; }
}

public partial class Alumnos_Horario
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Alumnos_Horario()
    {
        this.Asistencia = new HashSet<Asistencia>();
    }

    public int id_alumnohorario { get; set; }
    public string alumno { get; set; }
    public string grupo { get; set; }

    public virtual Alumnos Alumnos { get; set; }
    public virtual Grupos Grupos { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Asistencia> Asistencia { get; set; }
}

public partial class Asistencia
{
    public int id_asistencia { get; set; }
    public System.DateTime fecha { get; set; }
    public int alumnos_horarios { get; set; }
    public string estado { get; set; }

    public virtual Alumnos_Horario Alumnos_Horario { get; set; }
}

public partial class Docentes
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Docentes()
    {
        this.Horario_Materia = new HashSet<Horario_Materia>();
    }

    public string id_docente { get; set; }
    public string nombre { get; set; }
    public string apellido { get; set; }
    public string correo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Horario_Materia> Horario_Materia { get; set; }
}

public partial class Grupos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Grupos()
    {
        this.Alumnos_Horario = new HashSet<Alumnos_Horario>();
    }

    public string id_grupo { get; set; }
    public string horario_materia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Alumnos_Horario> Alumnos_Horario { get; set; }
    public virtual Horario_Materia Horario_Materia1 { get; set; }
}

public partial class horario
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public horario()
    {
        this.Horario_Materia = new HashSet<Horario_Materia>();
    }

    public int id_horario { get; set; }
    public System.TimeSpan hora { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Horario_Materia> Horario_Materia { get; set; }
}

public partial class Horario_Materia
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Horario_Materia()
    {
        this.Grupos = new HashSet<Grupos>();
    }

    public string codigo_horariomateria { get; set; }
    public int horario { get; set; }
    public string materia { get; set; }
    public string docente { get; set; }

    public virtual Docentes Docentes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Grupos> Grupos { get; set; }
    public virtual horario horario1 { get; set; }
    public virtual Materia Materia1 { get; set; }
}

public partial class Materia
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Materia()
    {
        this.Horario_Materia = new HashSet<Horario_Materia>();
    }

    public string id_materia { get; set; }
    public string nombre_materia { get; set; }
    public string facultad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Horario_Materia> Horario_Materia { get; set; }
}

public partial class MODULOS
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MODULOS()
    {
        this.OPERACIONES = new HashSet<OPERACIONES>();
    }

    public int CODMOD { get; set; }
    public string NOMBRE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OPERACIONES> OPERACIONES { get; set; }
}

public partial class OPERACIONES
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public OPERACIONES()
    {
        this.ROL_OPERA = new HashSet<ROL_OPERA>();
    }

    public int CODOPERA { get; set; }
    public string NOMOPERA { get; set; }
    public Nullable<int> CODMOD { get; set; }

    public virtual MODULOS MODULOS { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ROL_OPERA> ROL_OPERA { get; set; }
}

public partial class PERSONAS
{
    public int CODPERSONA { get; set; }
    public string NOMBRES { get; set; }
    public string APELLIDOS { get; set; }
    public string GENERO { get; set; }
    public Nullable<int> CODUSER { get; set; }

    public virtual USUARIO USUARIO { get; set; }
}

public partial class ROL_OPERA
{
    public int CODROLOPERA { get; set; }
    public Nullable<int> CODROL { get; set; }
    public Nullable<int> CODOPERA { get; set; }

    public virtual OPERACIONES OPERACIONES { get; set; }
    public virtual ROLES ROLES { get; set; }
}

public partial class ROLES
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ROLES()
    {
        this.ROL_OPERA = new HashSet<ROL_OPERA>();
        this.USUARIO = new HashSet<USUARIO>();
    }

    public int CODROL { get; set; }
    public string NOMROL { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ROL_OPERA> ROL_OPERA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<USUARIO> USUARIO { get; set; }
}

public partial class UserState
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserState()
    {
        this.USUARIO = new HashSet<USUARIO>();
    }

    public int CODESTADO { get; set; }
    public string Estado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<USUARIO> USUARIO { get; set; }
}

public partial class USUARIO
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public USUARIO()
    {
        this.PERSONAS = new HashSet<PERSONAS>();
    }

    public int CODUSER { get; set; }
    public string USUARIO1 { get; set; }
    public string PASSWORD { get; set; }
    public Nullable<System.DateTime> FECHA { get; set; }
    public Nullable<int> CODROL { get; set; }
    public Nullable<int> CODESTADO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PERSONAS> PERSONAS { get; set; }
    public virtual ROLES ROLES { get; set; }
    public virtual UserState UserState { get; set; }
}
