//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SEGURIDAD.Models.CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.PERSONAS = new HashSet<PERSONAS>();
        }
    
        public int CODUSER { get; set; }
        public string USUARIO1 { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> CODROL { get; set; }
        public Nullable<int> CODESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAS> PERSONAS { get; set; }
        public virtual ROLES ROLES { get; set; }
        public virtual UserState UserState { get; set; }
    }
}
